### ISSUE TITLE
Wrong path of library on index using grunt 

### ISSUE THREAD

**Issue by cis321** [omichelsen/angular-steps#2]
Hi! 
I followed your instructions and put <"script src="bower_components/angular-steps/angular-steps.js"><"/script"> on the index file. But, it didn't work because angular-steps.js is on dist directory. 
So, I corrected directly on index: <"script src="bower_components/angular-steps/dist/angular-steps.js"><"/script">. It works fine until I run grunt and rewrite the path to bower_components/angular-steps/angular-steps.js.

**Comment by omichelsen** [comment]
Hey, I've updated the docs to use the correct `dist` path.

I'm not quite sure if I understand how your grunt setup changes the path though?

**Comment by cis321** [comment]
Yes, my grunt setup change the path, when I run grunt serve. It put in the index the path "bower_components/angular-steps/angular-steps.js" automatically. It doesn't have dist directory on the path. I don't know where is the setting that indicate to grunt put the dependency on the index , I think there could be there the error. 

I resolve to use the last release v0.1.0.

**Comment by omichelsen** [comment]
That is probably the problem. The latest release i v0.2.1, which also fixes the paths that grunt/requirejs etc. looks at.

**Comment by cis321** [comment]
Sorry omichelsen, my bad I have the problem with 0.2.1 version.  I resolve to use the release 0.1.0. that it works fine.

**Comment by omichelsen** [comment]
I don't know what the problem might be then. Are you running `requirejs`, and can you show your setup?
