### ISSUE TITLE
missing steps-length availability

### ISSUE THREAD

**Issue by kloener** [omichelsen/angular-steps#4]
Hi, 

would be nice to have a steps-length to say something link "this is step 1 of 10".
I.e.:

`vm.stepsLength = StepsService.steps ('myNamedSteps').length;`

Unfortunately, your `StepsController` stores the `steps` inside of `$scope` instead of `this`. Otherwise `StepsService.steps ('myNamedSteps').steps.length;` would have worked.

regards,
Christian

**Comment by omichelsen** [comment]
Good idea, I will look into making it part of the public API.

**Comment by omichelsen** [comment]
I have exposed `steps` in the controller so you can get the length from `StepsService.steps ('myNamedSteps').length`. It is released as v0.3.0.
